// <auto-generated />
using System;
using AMS.Plugins.DapperSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Plugins.DapperSQL.Migrations
{
    [DbContext(typeof(AMSContext))]
    partial class AMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.CoreBusiness.BankTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.ToTable("transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 1000,
                            BranchId = 1,
                            BranchName = "City1",
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 2000,
                            BranchId = 2,
                            BranchName = "City2",
                            Date = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 3,
                            Amount = 3000,
                            BranchId = 3,
                            BranchName = "City3",
                            Date = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 4,
                            Amount = 4000,
                            BranchId = 4,
                            BranchName = "City4",
                            Date = new DateTime(2023, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AMS.CoreBusiness.BranchRecord", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<int>("EditLimit")
                        .HasColumnType("int");

                    b.HasKey("BranchId");

                    b.ToTable("branchRecords");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            EditLimit = 1
                        },
                        new
                        {
                            BranchId = 2,
                            EditLimit = 1
                        },
                        new
                        {
                            BranchId = 3,
                            EditLimit = 1
                        },
                        new
                        {
                            BranchId = 4,
                            EditLimit = 1
                        });
                });

            modelBuilder.Entity("AMS.CoreBusiness.YearRecord", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Year"));

                    b.Property<int>("EditLimit")
                        .HasColumnType("int");

                    b.HasKey("Year");

                    b.ToTable("yearRecords");

                    b.HasData(
                        new
                        {
                            Year = 2023,
                            EditLimit = 3
                        },
                        new
                        {
                            Year = 2024,
                            EditLimit = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
